export const eventstableColumns = [
  {
    id: "S.No",
    label: "S.No",
    minWidth: 70,
    align: "left",
  },
  {
    id: "createdAt",
    label: "Date of Creation",
    minWidth: 150,
    align: "left",
  },
  {
    id: "title",
    label: "Title",
    minWidth: 70,
    align: "left",
  },
  {
    id: "organizer",
    label: "Organizer",
    minWidth: 70,
    align: "left",
  },
  {
    id: "vendorId.email",
    label: "Vendor Email",
    minWidth: 70,
    align: "left",
  },
  {
    id: "datetime",
    label: "Start Date",
    minWidth: 200,
    align: "center",
  },
  {
    id: "enddatetime",
    label: "End Date",
    minWidth: 200,
    align: "center",
  },
  {
    id: "city",
    label: "City",
    minWidth: 100,
    align: "center",
  },
  // {
  //   id: "city",
  //   label: "Address",
  //   minWidth: 70,
  //   align: "center",
  // },
  // {
  //   id: "city",
  //   label: "Timming",
  //   minWidth: 70,
  //   align: "center",
  // },
  {
    id: "details",
    label: "Details",
    minWidth: 70,
    align: "center",
  },
  // {
  //   id: "isActive",
  //   label: "Status",
  //   minWidth: 70,
  //   align: "center",
  // },
  {
    id: "isActive",
    label: "Active",
    minWidth: 70,
    align: "center",
  },
  {
    id: "isPublished",
    label: "Published",
    minWidth: 70,
    align: "center",
  },
  {
    id: "action",
    label: "Action",
    minWidth: 100,
    align: "center",
  },
];

export const eventsFormFields = [
  {
    name: "title",
    label: "Title",
    type: "text",
    required: false,
    disabled: true,
  },
  {
    name: "type",
    label: "Event Type",
    type: "text",
    required: false,
    disabled: true,
  },
  {
    name: "organizer",
    label: "Organizer",
    type: "text",
    required: false,
    disabled: true,
  },
  {
    name: "startDate",
    label: "Event Start Date",
    type: "date",
    required: false,
  },
  {
    name: "startTime",
    label: "Event Start Time",
    type: "time",
    required: false,
  },
  {
    name: "endDate",
    label: "Event End Date",
    type: "date",
    required: false,
  },
  {
    name: "endTime",
    label: "Event End Time",
    type: "time",
    required: false,
  },
  {
    name: "address",
    label: "Address",
    type: "text",
    required: false,
    disabled: true,
  },
  {
    name: "city",
    label: "City",
    type: "text",
    required: false,
    disabled: true,
  },
  {
    name: "country",
    label: "Country",
    type: "text",
    required: false,
    disabled: true,
  },
];
